### ISSUE TITLE
pynixify -r requirements fails - do not know how to unpack source archive

### ISSUE THREAD

**Issue by InLaw** [cript0nauta/pynixify#33] opened 2020-08-12 16:19 UTC
Hello,

I would like to try your tool but get an error.

requirements_test_open.txt
```
dask
pyct
rasterio
numba
arcgis
datashape
```

pynixify -r requirements_test_open.txt
```
Resolving dask
Resolving pyct
Resolving rasterio
Resolving numba
Resolving arcgis
Resolving datashape
Resolving six (from PyPIPackage(attr=arcgis, version=1.8.2))
Resolving ipywidgets>=7 (from PyPIPackage(attr=arcgis, version=1.8.2))
Resolving widgetsnbextension>=3 (from PyPIPackage(attr=arcgis, version=1.8.2))
Resolving pandas>=1 (from PyPIPackage(attr=arcgis, version=1.8.2))
Resolving numpy>=1.16.2 (from PyPIPackage(attr=arcgis, version=1.8.2))
Resolving matplotlib (from PyPIPackage(attr=arcgis, version=1.8.2))
Resolving keyring>=19 (from PyPIPackage(attr=arcgis, version=1.8.2))
Resolving lerc (from PyPIPackage(attr=arcgis, version=1.8.2))
Resolving jupyterlab (from PyPIPackage(attr=arcgis, version=1.8.2))
Resolving pyshp>=2 (from PyPIPackage(attr=arcgis, version=1.8.2))
Resolving requests (from PyPIPackage(attr=arcgis, version=1.8.2))
Resolving requests-oauthlib (from PyPIPackage(attr=arcgis, version=1.8.2))
Resolving requests_toolbelt (from PyPIPackage(attr=arcgis, version=1.8.2))
Resolving requests_ntlm (from PyPIPackage(attr=arcgis, version=1.8.2))
Error parsing requirements of /nix/store/h4n1y7pl5qkmfq803vja9383pxk2mxmj-numba-0.48.0.tar.gz. Assuming it has no dependencies.
Resolving numpy>=1.7 (from NixPackage(attr=datashape, version=0.5.4))
Resolving multipledispatch>=0.4.7 (from NixPackage(attr=datashape, version=0.5.4))
Resolving python-dateutil (from NixPackage(attr=datashape, version=0.5.4))
Resolving param>=1.7.0 (from NixPackage(attr=pyct, version=0.4.6))
Error parsing requirements of /nix/store/jcmvcpqzznd6a1ldhkbv60zv1x9n887i-source. Assuming it has no dependencies.
Error parsing requirements of /nix/store/2h4zpacjqwwn4jp8i6mz1z8ipvr9yysf-numpy-1.18.1.zip. Assuming it has no dependencies.
Error parsing requirements of /nix/store/8k0b76qijmdm1i0zd34l5nx6m7ppa1ln-pandas-1.0.1.tar.gz. Assuming it has no dependencies.
Error parsing requirements of /nix/store/s6rqrafbg0wxh9k38qc1kfmkbgmjk7dh-ipywidgets-7.5.1.tar.gz. Assuming it has no dependencies.
Resolving notebook>=4.4.1 (from NixPackage(attr=widgetsnbextension, version=3.5.1))
Resolving notebook>=4.3.1 (from NixPackage(attr=jupyterlab, version=1.2.6))
Resolving tornado!=6.0.0,!=6.0.1,!=6.0.2 (from NixPackage(attr=jupyterlab, version=1.2.6))
Resolving jupyterlab_server~=1.0.0 (from NixPackage(attr=jupyterlab, version=1.2.6))
Resolving jinja2>=2.10 (from NixPackage(attr=jupyterlab, version=1.2.6))
Resolving cycler>=0.10 (from NixPackage(attr=matplotlib, version=3.1.3))
Resolving kiwisolver>=1.0.1 (from NixPackage(attr=matplotlib, version=3.1.3))
Resolving pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 (from NixPackage(attr=matplotlib, version=3.1.3))
Resolving python-dateutil>=2.1 (from NixPackage(attr=matplotlib, version=3.1.3))
Resolving numpy>=1.11 (from NixPackage(attr=matplotlib, version=3.1.3))
Resolving chardet<3.1.0,>=3.0.2 (from NixPackage(attr=requests, version=2.22.0))
Resolving idna<2.9,>=2.5 (from NixPackage(attr=requests, version=2.22.0))
Resolving urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 (from NixPackage(attr=requests, version=2.22.0))
Resolving certifi>=2017.4.17 (from NixPackage(attr=requests, version=2.22.0))
Resolving oauthlib>=3.0.0 (from NixPackage(attr=requests_oauthlib, version=1.3.0))
Resolving requests>=2.0.0 (from NixPackage(attr=requests_oauthlib, version=1.3.0))
Resolving requests<3.0.0,>=2.0.1 (from NixPackage(attr=requests-toolbelt, version=0.9.1))
Resolving six>=1.5 (from NixPackage(attr=dateutil, version=2.8.1))
Resolving requests>=2.0.0 (from NixPackage(attr=requests_ntlm, version=1.1.0))
Resolving ntlm-auth>=1.0.2 (from NixPackage(attr=requests_ntlm, version=1.1.0))
Resolving cryptography>=1.3 (from NixPackage(attr=requests_ntlm, version=1.1.0))
Error parsing requirements of /nix/store/p95d312gkcanzwfmq0c2zaryicpnda4d-multipledispatch-0.6.0.tar.gz. Assuming it has no dependencies.
Resolving jinja2 (from NixPackage(attr=notebook, version=6.0.3))
Resolving tornado>=5.0 (from NixPackage(attr=notebook, version=6.0.3))
Resolving pyzmq>=17 (from NixPackage(attr=notebook, version=6.0.3))
Resolving ipython_genutils (from NixPackage(attr=notebook, version=6.0.3))
Resolving traitlets>=4.2.1 (from NixPackage(attr=notebook, version=6.0.3))
Resolving jupyter_core>=4.6.1 (from NixPackage(attr=notebook, version=6.0.3))
Resolving jupyter_client>=5.3.4 (from NixPackage(attr=notebook, version=6.0.3))
Resolving nbformat (from NixPackage(attr=notebook, version=6.0.3))
Resolving nbconvert (from NixPackage(attr=notebook, version=6.0.3))
Resolving ipykernel (from NixPackage(attr=notebook, version=6.0.3))
Resolving Send2Trash (from NixPackage(attr=notebook, version=6.0.3))
Resolving terminado>=0.8.1 (from NixPackage(attr=notebook, version=6.0.3))
Resolving prometheus_client (from NixPackage(attr=notebook, version=6.0.3))
Resolving MarkupSafe>=0.23 (from NixPackage(attr=jinja2, version=2.11.1))
Resolving json5 (from NixPackage(attr=jupyterlab_server, version=1.0.6))
Resolving jsonschema>=3.0.1 (from NixPackage(attr=jupyterlab_server, version=1.0.6))
Resolving notebook>=4.2.0 (from NixPackage(attr=jupyterlab_server, version=1.0.6))
Resolving jinja2>=2.10 (from NixPackage(attr=jupyterlab_server, version=1.0.6))
Resolving six (from NixPackage(attr=cycler, version=0.10.0))
Resolving setuptools (from NixPackage(attr=kiwisolver, version=1.1.0))
Resolving six>=1.4.1 (from NixPackage(attr=cryptography, version=2.8))
Resolving cffi!=1.11.3,>=1.8 (from NixPackage(attr=cryptography, version=2.8))
Error parsing requirements of /nix/store/s13gbparr4n4wppjhgdiqxr80yn00908-pyzmq-18.1.1.tar.gz. Assuming it has no dependencies.
Error parsing requirements of /nix/store/ra6bxwplwqfiwhvrq1jczab6xzjmh3kd-ipython_genutils-0.2.0.tar.gz. Assuming it has no dependencies.
Error parsing requirements of /nix/store/22vsk6il17m01amgdlfjasx0p80rvcra-traitlets-4.3.3.tar.gz. Assuming it has no dependencies.
Resolving attrs>=17.4.0 (from NixPackage(attr=jsonschema, version=3.2.0))
Resolving pyrsistent>=0.14.0 (from NixPackage(attr=jsonschema, version=3.2.0))
Resolving setuptools (from NixPackage(attr=jsonschema, version=3.2.0))
Resolving six>=1.11.0 (from NixPackage(attr=jsonschema, version=3.2.0))
Resolving traitlets (from NixPackage(attr=jupyter_client, version=5.3.4))
Resolving jupyter_core>=4.6.0 (from NixPackage(attr=jupyter_client, version=5.3.4))
Resolving pyzmq>=13 (from NixPackage(attr=jupyter_client, version=5.3.4))
Resolving python-dateutil>=2.1 (from NixPackage(attr=jupyter_client, version=5.3.4))
Resolving tornado>=4.1 (from NixPackage(attr=jupyter_client, version=5.3.4))
Error parsing requirements of /nix/store/dw7fjmk7hd20q9kn93vr6805jhr3b8p3-nbformat-5.0.4.tar.gz. Assuming it has no dependencies.
Resolving mistune<2,>=0.8.1 (from NixPackage(attr=nbconvert, version=5.6.1))
Resolving jinja2>=2.4 (from NixPackage(attr=nbconvert, version=5.6.1))
Resolving pygments (from NixPackage(attr=nbconvert, version=5.6.1))
Resolving traitlets>=4.2 (from NixPackage(attr=nbconvert, version=5.6.1))
Resolving jupyter_core (from NixPackage(attr=nbconvert, version=5.6.1))
Resolving nbformat>=4.4 (from NixPackage(attr=nbconvert, version=5.6.1))
Resolving entrypoints>=0.2.2 (from NixPackage(attr=nbconvert, version=5.6.1))
Resolving bleach (from NixPackage(attr=nbconvert, version=5.6.1))
Resolving pandocfilters>=1.4.1 (from NixPackage(attr=nbconvert, version=5.6.1))
Resolving testpath (from NixPackage(attr=nbconvert, version=5.6.1))
Resolving defusedxml (from NixPackage(attr=nbconvert, version=5.6.1))
Error parsing requirements of /nix/store/5vc1ni6l9yamkz8idfhy4ybpdkiny5af-terminado-0.8.3.tar.gz. Assuming it has no dependencies.
Resolving traitlets (from NixPackage(attr=jupyter_core, version=4.6.1))
Error parsing requirements of /nix/store/jxira8sfpg1963wvw0f30rach667zb09-setuptools-44.0.0-sdist.tar.gz. Assuming it has no dependencies.
Error parsing requirements of /nix/store/w3q7rfadyf86ylc3xs7hgh45ypm2k97z-ipykernel-5.1.4.tar.gz. Assuming it has no dependencies.
Resolving pycparser (from NixPackage(attr=cffi, version=1.13.2))
Resolving six (from NixPackage(attr=pyrsistent, version=0.15.6))
Resolving six>=1.9.0 (from NixPackage(attr=bleach, version=3.1.0))
Resolving webencodings (from NixPackage(attr=bleach, version=3.1.0))
Error parsing requirements of /nix/store/26g6ql309qr2n1wvr8nmmi64603sg7r8-entrypoints-0.3.tar.gz. Assuming it has no dependencies.
Error parsing requirements of /nix/store/vs3agvip9jl7clcfq3zcxmssj8qh63j8-pandocfilters-1.4.2.tar.gz. Assuming it has no dependencies.
these derivations will be built:
  /nix/store/pw9p7wcaw04pq6j4pj726iv1xbqwnjl9-setup.py_data_r4n6iw75jdad454ihmlawyw295kr2s78-testpath-0.drv
building '/nix/store/pw9p7wcaw04pq6j4pj726iv1xbqwnjl9-setup.py_data_r4n6iw75jdad454ihmlawyw295kr2s78-testpath-0.drv'...
unpacking sources
unpacking source archive /nix/store/ixv8qqnk1yakpd7ll3ysf8qcsabgd3c9-r4n6iw75jdad454ihmlawyw295kr2s78-testpath-0.4.4-py2.py3-none-any.whl
do not know how to unpack source archive /nix/store/ixv8qqnk1yakpd7ll3ysf8qcsabgd3c9-r4n6iw75jdad454ihmlawyw295kr2s78-testpath-0.4.4-py2.py3-none-any.whl
builder for '/nix/store/pw9p7wcaw04pq6j4pj726iv1xbqwnjl9-setup.py_data_r4n6iw75jdad454ihmlawyw295kr2s78-testpath-0.drv' failed with exit code 1
error: --- Error --- nix-build
build of '/nix/store/pw9p7wcaw04pq6j4pj726iv1xbqwnjl9-setup.py_data_r4n6iw75jdad454ihmlawyw295kr2s78-testpath-0.drv' failed

/nix/store/r94aa2gj4drkhfvkm2p4ab6cblb6kxlq-python3-3.7.6/lib/python3.7/asyncio/unix_events.py:878: RuntimeWarning: A loop is being detached from a child watcher with pending handlers
  RuntimeWarning)
Traceback (most recent call last):
  File "/nix/store/x1mvha3yrd4ds91ryginp7fd4mgkid8s-python3.7-pynixify-0.1/bin/..pynixify-wrapped-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/x1mvha3yrd4ds91ryginp7fd4mgkid8s-python3.7-pynixify-0.1/lib/python3.7/site-packages/pynixify/command.py", line 159, in main
    max_jobs=args.max_jobs,
  File "/nix/store/r94aa2gj4drkhfvkm2p4ab6cblb6kxlq-python3-3.7.6/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/nix/store/r94aa2gj4drkhfvkm2p4ab6cblb6kxlq-python3-3.7.6/lib/python3.7/asyncio/base_events.py", line 583, in run_until_complete
    return future.result()
  File "/nix/store/x1mvha3yrd4ds91ryginp7fd4mgkid8s-python3.7-pynixify-0.1/lib/python3.7/site-packages/pynixify/command.py", line 197, in _main_async
    for req in all_requirements
  File "/nix/store/x1mvha3yrd4ds91ryginp7fd4mgkid8s-python3.7-pynixify-0.1/lib/python3.7/site-packages/pynixify/version_chooser.py", line 112, in require
    for req in (reqs.runtime_requirements + reqs.test_requirements)
  File "/nix/store/x1mvha3yrd4ds91ryginp7fd4mgkid8s-python3.7-pynixify-0.1/lib/python3.7/site-packages/pynixify/version_chooser.py", line 112, in require
    for req in (reqs.runtime_requirements + reqs.test_requirements)
  File "/nix/store/x1mvha3yrd4ds91ryginp7fd4mgkid8s-python3.7-pynixify-0.1/lib/python3.7/site-packages/pynixify/version_chooser.py", line 112, in require
    for req in (reqs.runtime_requirements + reqs.test_requirements)
  [Previous line repeated 1 more time]
  File "/nix/store/x1mvha3yrd4ds91ryginp7fd4mgkid8s-python3.7-pynixify-0.1/lib/python3.7/site-packages/pynixify/version_chooser.py", line 104, in require
    reqs: PackageRequirements = await self.evaluate_requirements(pkg)
  File "/nix/store/x1mvha3yrd4ds91ryginp7fd4mgkid8s-python3.7-pynixify-0.1/lib/python3.7/site-packages/pynixify/version_chooser.py", line 145, in evaluate_package_requirements
    return await eval_path_requirements(src)
  File "/nix/store/x1mvha3yrd4ds91ryginp7fd4mgkid8s-python3.7-pynixify-0.1/lib/python3.7/site-packages/pynixify/package_requirements.py", line 57, in eval_path_requirements
    str(path.resolve())
  File "/nix/store/x1mvha3yrd4ds91ryginp7fd4mgkid8s-python3.7-pynixify-0.1/lib/python3.7/site-packages/pynixify/nixpkgs_sources.py", line 146, in run_nix_build
    return await _run_nix_build(*args, retries=retries, max_retries=5)
  File "/nix/store/x1mvha3yrd4ds91ryginp7fd4mgkid8s-python3.7-pynixify-0.1/lib/python3.7/site-packages/pynixify/nixpkgs_sources.py", line 129, in _run_nix_build
    raise NixBuildError(f'nix-build failed with code {status}')
pynixify.exceptions.NixBuildError: nix-build failed with code 100
```

**Comment by cript0nauta** [comment] 2020-08-12 18:16
Hi, thanks for reporting! Your requirements triggered two different bugs in pynixify:

1. Parsing the dependencies of Nixpkgs whose source is a wheel, such as `testpath`, was failing. I fixed this in 39eb4b4d035fed045f3af3a1e3ee65616cf8a7d6.
2. The arcgis package uses `lerc` which is a build requirement of arcgis instead of a runtime requirement. This made pynixify fail to detect it. I pushed a workaround for this issue in 0242fac55528639aad552f8cf0460bb0956f17ef.

Running a `git pull` and reinstalling should work with your pasted `requirements_test_open.txt` file now.

Note that the created `lerc` expression won't work properly because the package it's written in C. This means the "raster" feature of arcgis, which uses lerc, might not work properly. Other parts of arcgis not using lerc should work fine.

Let me know if these fixes work so I can close the issue. Thanks again for reporting the bugs!

**Comment by cript0nauta** [comment] 2020-08-12 18:41
Oops, the last change introduced a regression, I rolled it back for now and will inspect it.

**Comment by InLaw** [comment] 2020-08-12 18:51
if it helps
[Duplicated packages in closure of package 'arcgis'](https://github.com/DavHau/mach-nix/issues/64)

**Comment by cript0nauta** [comment] 2020-08-12 19:55
Just fixed the regression and merged the changes into the main branch. It should work ok now.

**Closed** 2020-08-13 11:14 UTC
