### ISSUE TITLE
Can't use pynixify on mac os x

### ISSUE THREAD

**Issue by nbren12** [cript0nauta/pynixify#53] opened 2021-03-11 05:35 UTC
pynixify gives an error on my mac:

```
$ pynixify --nixpkgs https://github.com/nixos/nixpkgs/archive/20.09.tar.gz numpy
error: Unsupported system
(use '--show-trace' to show detailed location information)
Traceback (most recent call last):
  File "/tmp/tmp.HGWx6HJGHn/bin/pynixify", line 33, in <module>
    sys.exit(load_entry_point('pynixify', 'console_scripts', 'pynixify')())
  File "/Users/noah/tmp/pynixify/pynixify/command.py", line 150, in main
    asyncio.run(_main_async(
  File "/nix/store/b3mgl5x2233qddyh3rfdss7ngzwa8bgq-python3-3.8.5/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/nix/store/b3mgl5x2233qddyh3rfdss7ngzwa8bgq-python3-3.8.5/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/noah/tmp/pynixify/pynixify/command.py", line 179, in _main_async
    version_chooser: VersionChooser = await _build_version_chooser(
  File "/Users/noah/tmp/pynixify/pynixify/command.py", line 59, in _build_version_chooser
    nixpkgs_data = NixpkgsData(await load_nixpkgs_data({}))
  File "/Users/noah/tmp/pynixify/pynixify/nixpkgs_sources.py", line 109, in load_nixpkgs_data
    assert status == 0
AssertionError
```
It's not clear to me what the problem is, but I think the `nix-instantiate` call is choking on some package.

Any suggestions? Thanks!

**Comment by nbren12** [comment] 2021-03-11 05:39
I manually edited the pynixify source to print the nix-instantiate call, and then ran it as follows. Here is a more detailed error mesage:
```
$ nix-instantiate --eval --strict --json /Users/noah/tmp/pynixify/pynixify/data/pythonPackages.nix -I nixpkgs=https://github.com/nixos/nixpkgs/archive/20.09.tar.gz --show-trace
error: while evaluating 'pipe' at /Users/noah/tmp/pynixify/pynixify/data/pythonPackages.nix:65:10, called from /Users/noah/tmp/pynixify/pynixify/data/pythonPackages.nix:72:4:
while evaluating 'foldl' at /nix/store/vffdfp5gnspq3mdid9wk5p15hmv3ci4z-20.09.tar.gz/lib/lists.nix:80:20, called from /Users/noah/tmp/pynixify/pynixify/data/pythonPackages.nix:69:8:
while evaluating 'foldl'' at /nix/store/vffdfp5gnspq3mdid9wk5p15hmv3ci4z-20.09.tar.gz/lib/lists.nix:82:16, called from /nix/store/vffdfp5gnspq3mdid9wk5p15hmv3ci4z-20.09.tar.gz/lib/lists.nix:86:8:
while evaluating anonymous function at /Users/noah/tmp/pynixify/pynixify/data/pythonPackages.nix:69:24, called from /nix/store/vffdfp5gnspq3mdid9wk5p15hmv3ci4z-20.09.tar.gz/lib/lists.nix:85:14:
while evaluating 'groupBy'' at /nix/store/vffdfp5gnspq3mdid9wk5p15hmv3ci4z-20.09.tar.gz/lib/lists.nix:343:29, called from /Users/noah/tmp/pynixify/pynixify/data/pythonPackages.nix:69:27:
while evaluating anonymous function at /nix/store/vffdfp5gnspq3mdid9wk5p15hmv3ci4z-20.09.tar.gz/lib/lists.nix:344:16, called from /nix/store/vffdfp5gnspq3mdid9wk5p15hmv3ci4z-20.09.tar.gz/lib/lists.nix:344:5:
while evaluating anonymous function at /Users/noah/tmp/pynixify/pynixify/data/pythonPackages.nix:78:17, called from /nix/store/vffdfp5gnspq3mdid9wk5p15hmv3ci4z-20.09.tar.gz/lib/lists.nix:346:23:
while evaluating the attribute 'pypiName' at /Users/noah/tmp/pynixify/pynixify/data/pythonPackages.nix:59:9:
while evaluating 'urlToPypiName' at /Users/noah/tmp/pynixify/pynixify/data/pythonPackages.nix:33:19, called from /Users/noah/tmp/pynixify/pynixify/data/pythonPackages.nix:59:41:
while evaluating the attribute 'src' at /Users/noah/tmp/pynixify/pynixify/data/pythonPackages.nix:24:9:
while evaluating the attribute 'src' at /nix/store/vffdfp5gnspq3mdid9wk5p15hmv3ci4z-20.09.tar.gz/pkgs/development/python-modules/pytorch/bin.nix:30:3:
Unsupported system
```

**Comment by cript0nauta** [comment] 2021-03-11 06:15
It looks like some parts of pytorch fail to instantiate on OSX. Could you run `nix-build '<nixpkgs>' --show-trace -A python3Packages.pytorch` in your machine and share its output? In case it fails, this issue will most likely need to be fixed in nixpkgs.

**Comment by nbren12** [comment] 2021-03-12 16:54
`nix-build` gives a more informative error message (below). The problem is with the `pytorch-bin` package rather than `pytorch`:
```
 nix-build '<nixpkgs>' --show-trace -A python3Packages.pytorch-bin                                                                                                           (base)
error: --- ThrownError ---------------------------------------------------------------------------------------------------------------------------------------------------- nix-build
Package ‘python3.8-pytorch-1.6.0’ in /nix/store/5khy8k79c5d4xqv0pg3xvgzf51gd5hg0-nixpkgs-20.09.3072.d4c29df154d/nixpkgs/pkgs/development/python-modules/pytorch/bin.nix:62 is not supported on ‘x86_64-darwin’, refusing to evaluate.

a) For `nixos-rebuild` you can set
  { nixpkgs.config.allowUnsupportedSystem = true; }
in configuration.nix to override this.

b) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
  { allowUnsupportedSystem = true; }
to ~/.config/nixpkgs/config.nix.
```

**Comment by nbren12** [comment] 2021-03-12 17:02
It still doesn't work after adding that configuration.

**Comment by nbren12** [comment] 2021-03-12 17:22
I think the problem is in this line: 
```
let 
  unsupported = throw "Unsupported system";
....
in ...
  src = fetchurl srcs."${stdenv.system}-${pyVerNoDot}" or unsupported;
```

I wonder why this line in pynixify doesn't seem to catch this error https://github.com/cript0nauta/pynixify/blob/7622a24dc6199296ced5ff37d520384f7a4a7274/pynixify/data/pythonPackages.nix#L74

**Comment by nbren12** [comment] 2021-03-12 17:36
Ok. I think the error is not being caught because of nix's lazy evaluation. See this explanation from https://nixos.org/manual/nix/stable/:

<img width="977" alt="Screen Shot 2021-03-12 at 9 35 29 AM" src="https://user-images.githubusercontent.com/1386642/110976891-53993200-8316-11eb-9499-c062e9cd66b7.png">


Would you be open to a PR using `builtins.deepSeq`?

**Comment by cript0nauta** [comment] 2021-03-12 17:45
You're right, the problem seems to be caused by nix's lazy evaluation. I'm not sure if using `builtins.deepSeq` would be the best solution, since it might cause infinite recursion errors or be considerably slower than simply using `tryEval`. But we should definitely try it and evaluate its impact.

Let me check that the tests are working ok (I think they are broken when using nixos-unstable). Once they're fixed we can try using `deepSeq` and ensure it doesn't add any regressions.

**Comment by cript0nauta** [comment] 2021-03-12 18:48
Tests are passing now in the main branch. PRs adressing this issue are more than welcome :)

Let me know if I can help you with any troubles you might encounter.

**Comment by nbren12** [comment] 2021-03-12 19:09
Yah. I ran into some other issues using deepSeq, but I think pushing the tryEval to where the `.src` attribute is referenced should work.

**Closed** 2021-03-12 22:52 UTC
